changelog:
  exclude:
    labels:
      - tagpr
      - ci
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - feat
    - title: Bug fixes
      labels:
        - fix
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
