version: "3"
services:
  mysql8:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --plugin-load-add=mysql_no_login.so
    networks:
      - default
    ports:
      - "33306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
