name: Release

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  GPG_PRIVATE_KEY:
    description: GPG private key
    required: true
  PASSPHRASE:
    description: GPG passphrase
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        # Allow goreleaser to access older tag information.
        fetch-depth: 0
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@72b6676b71ab476b77e676928516f6982eef7a41 # v5.3.0
      id: import_gpg
      with:
        gpg_private_key: ${{ inputs.GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.PASSPHRASE }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
      with:
        args: release --clean
      env:
        # GitHub sets the GITHUB_TOKEN secret automatically.
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
