name: Release

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  GPG_PRIVATE_KEY:
    description: GPG private key
    required: true
  PASSPHRASE:
    description: GPG passphrase
    required: true
  TAG_NAME:
    description: Git tag name
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        # Allow goreleaser to access older tag information.
        fetch-depth: 0
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
      id: import_gpg
      with:
        gpg_private_key: ${{ inputs.GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.PASSPHRASE }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
      with:
        args: release --clean
      env:
        # GitHub sets the GITHUB_TOKEN secret automatically.
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
